config/routes.rb
MusicApp::Application.routes.draw do
  resources :bands
  resources :albums
  resources :tracks
  resources :notes
  resource :session

  get "/users/activate", :to => 'users#activate'

  resources :users


end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :name, :is_live

  has_many(
        :tracks,
        :class_name => "Track",
        :foreign_key => :album_id,
        :primary_key => :id,
        :dependent => :destroy
        )

  belongs_to(
        :band,
        :class_name => "Band",
        :foreign_key => :band_id,
        :primary_key => :id
        )


end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many(
          :albums,
          :class_name => "Album",
          :foreign_key => :band_id,
          :primary_key => :id,
          :dependent  => :destroy
          )

  has_many(
        :tracks,
        :through => :albums,
        :source => :tracks
        )

  validates :name, :presence => true, :uniqueness => true
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :track_id, :user_id
  validates :body, :presence  => true

  belongs_to(:track,
  :class_name => "Track",
  :primary_key => :id,
  :foreign_key => :track_id
  )
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :name, :is_bonus, :lyrics

  belongs_to(
      :album,
      :class_name => "Album",
      :foreign_key => :album_id,
      :primary_key => :id
      )

  has_one(
    :band,
    :through => :album,
    :source => :band
    )

  has_many( :notes,
    :class_name => "Note",
    :foreign_key => :track_id,
    :primary_key => :id
    )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :activation_token, :email, :password, :token
  before_validation :generate_activation_token,
                    :generate_token,
                    :on => :create
  validates :email, :password, :presence => true
  validates :email, :uniqueness => true

  def generate_activation_token
    self.activation_token = SecureRandom.urlsafe_base64
  end

  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @all_albums = Album.all
  end

  def create
    band = Band.find_by_id(params[:band][:id])
    album = band.albums.create!(params[:album])
    redirect_to album_url(album)
  end

  def destroy
    album = Album.find_by_id(params[:id])
    band = album.band
    album.destroy
    flash[:notices] ||= []
    flash[:notices] << "Album removed"

    redirect_to band_url(band)
  end

  def edit
    @album = Album.find_by_id(params[:id])
    @all_bands = Band.all
  end

  def new
    @all_bands = Band.all
    @album = Album.new
  end

  def show
    @album = Album.find_by_id(params[:id])
  end

  def update
    params[:album][:band_id] = params[:band][:id]
    album = Album.find_by_id(params[:id])
    album.update_attributes!(params[:album])

    redirect_to album_url(album)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :logged_in
  before_filter :authorized, :only => [:destroy]

  def current_user
    @current_user ||= User.find_by_token(session[:session_token])
  end

  def logged_in
    redirect_to new_session_url if current_user.nil?
  end

  def authorized
    flash[:notices] ||= []
    unless params[:controller] == :notes
      unless @current_user.is_admin
        flash[:notices] << "You aren't allowed to delete that."
        redirect_to :back
      end
    end
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @all_bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.create!(params[:band])
    redirect_to band_url(@band)
  end

  def edit
    @band = Band.find_by_id(params[:id])
    render :edit
  end

  def update
    band = Band.find_by_id(params[:id])
    band.update_attributes!(params[:band])

    redirect_to band_url(band)
  end

  def destroy
    band = Band.find_by_id(params[:id])
    band.destroy
    flash[:notices] ||= []
    flash[:notices] << "Band removed"

    redirect_to bands_url
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  skip_before_filter :authorized, :only => [:destroy]

  def create
    note = Note.create!(params[:note])
    redirect_to track_url(note.track_id)
  end

  def destroy
    note = Note.find_by_id(params[:id])

    unless @current_user.is_admin || current_user.id == note.user_id
      flash[:notices] ||= []
      flash[:notices] << "You aren't allowed to delete that."
      redirect_to :back
    else
      track = note.track
      note.destroy
      redirect_to track_url(track)
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :logged_in, :only => [:create, :new]

  def create
    #log in
    user = User.find_by_email(params[:email])
    if params[:password] == user.password && user.activated
      session[:session_token] = user.token

      redirect_to user_url(user)
    else
      flash[:notices] ||= []
      flash[:notices] << "Login failed"

      redirect_to new_session_url
    end
  end

  def destroy

  end

  def new
    render :new
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @all_tracks = Track.all
  end

  def show
    @track = Track.find_by_id(params[:id])
    render :show
  end

  def new
    @all_albums = Album.all
    @track = Track.new
    render :new
  end

  def create
    album = Album.find_by_id(params[:album][:id])
    track = album.tracks.create!(params[:track])

    redirect_to track_url(track)
  end

  def edit
    @all_albums = Album.all
    @track = Track.find_by_id(params[:id])
    render :edit
  end

  def update
    params[:track][:album_id] = params[:album][:id]
    track = Track.find_by_id(params[:id])
    track.update_attributes!(params[:track])

    redirect_to track_url(track)
  end

  def destroy
    track = Track.find_by_id(params[:id])
    album = track.album
    track.destroy
    flash[:notices] ||= []
    flash[:notices] << "Track removed"

    redirect_to album_url(album)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :logged_in, :only => [:new, :create, :activate]

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    user = User.create!(params[:user])
    UserMailer.activation_email(user).deliver!
    render :text => "Check your email to activate your account!"
  end

  def activate
    user = User.find_by_activation_token(params[:activation_token])
    user.activated = true
    user.save!

    redirect_to new_session_url
  end


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    lines_array = lyrics.split("\n")
    lines_array.map!{ |line| "&#9835;" << h(line) }
    new_lyrics = lines_array.join("\n")
    "<pre>#{new_lyrics}</pre>".html_safe
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% action_url = action == :new ? albums_url : album_url(album) %>

<form action="<%=action_url%>" method="post">
		<% if action == :edit %>
			<input type="hidden" name="_method" value="put">
		<% end %>

		<label for="band_id">Choose Band:</label>
		<select name="band[id]" id="band_id">
			<% all_bands.each do |band| %>
			<option value="<%= band.id %>" <%= 'selected = "selected"'.html_safe if (album.persisted? && album.band.id == band.id) %> ><%= band.name %> </option>
			<%end%>
		</select>


	<label for="album_name">Album</label>
	<input name="album[name]" type="text" id="album_name" value = "<%=album.name%>">

	<label for="album_is_live">Live</label>
	<input type="radio" name="album[is_live]" value="true" id="album_is_live" <%="checked".html_safe if album.is_live%>>

	<label for="album_is_live">Studio</label>
	<input type="radio" name="album[is_live]" value="false" id="album_is_live" <%="checked".html_safe if !album.is_live%>>

	<input type="submit" value="Complete album">
</form>

app/views/albums/edit.html.erb
<%= render :partial  =>  "form", :locals => { :album  => @album, :all_bands => @all_bands, :action  => :edit }%>

app/views/albums/index.html.erb
<% @all_albums.each do |album| %>
<div><%= link_to album.name, album_url(album) %> </div>
<%end%>

app/views/albums/new.html.erb
<%= render :partial  =>  "form", :locals => { :album  => @album, :all_bands => @all_bands,:action  => :new }%>

app/views/albums/show.html.erb
<h2><%= @album.name %> by
	<%= link_to @album.band.name, band_url(@album.band) %>

	<%= " (Live)" if @album.is_live %>

</h2>

<ul>
	<% @album.tracks.each do |track|%>
	<li>
		<form action="<%=track_url(track)%>" method="post">
			<%= link_to track.name, track_url(track) %>
			<input type="hidden" name="_method" value="delete">
			<input type="submit" value="Delete track">
		</form>
	</li>
	<% end %>
</ul>

app/views/bands/_form.html.erb
<% action_url = action == :new ? bands_url : band_url(band) %>


<form action="<%=action_url%>" method="post">
	<% if action == :edit %>
		<input type="hidden" name="_method" value="put">
	<% end %>
	<label for="band_name">Band</label>
		<input name="band[name]" value="<%=band.name%>" type = "text" id = "band_name">
		<input type="submit" value="Complete band">
</form>

app/views/bands/edit.html.erb
<%= render :partial => "form",
:locals => { :band => @band, :action => :edit } %>

app/views/bands/index.html.erb
<% @all_bands.each do |band| %>
<div><%= link_to band.name, band_url(band) %> </div>
<%end%>

app/views/bands/new.html.erb
<%= render :partial => "form",
:locals => { :band => @band, :action => :new } %>

app/views/bands/show.html.erb
<div><%=@band.name%></div>

<ul>
	<% @band.albums.each do |album| %>
	<li>
		<form action="<%=album_url(album)%>" method="post">
			<%= link_to album.name, album_url(album)%>
			<input type="hidden" name="_method" value="delete">
			<input type="submit" value="Delete album">
		</form>
		<ul>
			<% album.tracks.each do |track| %>
				<li>
					<form action="<%=track_url(track)%>" method="post">
						<%= link_to track.name, track_url(track) %>
						<input type="hidden" name="_method" value="delete">
						<input type="submit" value="Delete track">
					</form>
				</li>
			<% end %>
		</ul>
	</li>
	<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%unless flash[:notices].nil?%>
	<%flash[:notices].each do |notice|%>
	<div><%=notice%></div>
	<%end%>
<%end%>
<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<form action="<%= note_url(note) %>" method="post">
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token %>">
	<input type="hidden" name="_method" value="delete">
	<%= note.body %>
	<% if @current_user.is_admin || @current_user.id == note.user_id %>
	<input type="submit" value="Delete note">
	<% end %>
</form>

app/views/shared/_delete.html.erb
<!-- TODO: build out delete partial -->

app/views/tracks/_form.html.erb
<% action_url = action == :new ? tracks_url : track_url(track) %>

<form action="<%=action_url%>" method="post">
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token %>">
	<% if action == :edit %>
		<input type="hidden" name="_method" value="put">
	<% end %>
	<div>
		<label for="album_id">Choose Album:</label>
		<select name="album[id]" id="album_id">
			<% all_albums.each do |album| %>
			<option <%= 'selected = "selected"'.html_safe if (track.persisted? && track.album.id == album.id) %> value="<%= album.id %>" >
				<%= album.name %>
			</option>
			<%end%>
		</select>


		<label for="track_name">Track</label>
		<input name="track[name]" type="text" id="track_name" value="<%=track.name %>">

		<label for="track_is_bonus">Bonus</label>
		<input type="radio" name="track[is_bonus]" value="true" id="track_is_bonus"
		<%= 'checked'.html_safe if track.is_bonus %>>

		<label for="track_is_bonus">Regular</label>
		<input type="radio" name="track[is_bonus]" value="false" id="track_is_bonus" <%= 'checked'.html_safe unless track.is_bonus %>>
	</div>

	<div>
		<label for="track_lyrics">Lyrics</label><br />
		<textarea name="track[lyrics]" id="track_lyrics"><%=track.lyrics%></textarea>
	</div>

	<input type="submit" value="Add track">
</form>

app/views/tracks/edit.html.erb
<%= render :partial => "form",
:locals => { :track => @track,
						:all_albums => @all_albums,
						:action => :edit } %>

app/views/tracks/index.html.erb
<% @all_tracks.each do |track| %>
<div><%= link_to track.name, track_url(track) %> </div>
<%end%>

app/views/tracks/show.html.erb
<%= @track.name %>
by <%= link_to @track.band.name, band_url(@track.band) %>
on <%= link_to @track.album.name, album_url(@track.album) %>
<%= " (bonus track)" if @track.is_bonus %>

Lyrics:
<div>
	<%=ugly_lyrics(@track.lyrics)%>
</div>

<form action="<%=track_url(@track)%>" method="post">
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token %>">
	<input type="hidden" name="_method" value="delete">
	<input type="submit" value="Delete track">
</form>
<br />
<br />

<%= render @track.notes %>

<form action="<%=notes_url%>" method="post">
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token %>">
	<input type="hidden" name="note[track_id]" value="<%=@track.id%>">
	<input type="hidden" name="note[user_id]" value="<%=@current_user.id%>">
	<label for="note_body">
	<textarea name="note[body]" id="note_body"> </textarea><br />
	<input type="submit" value="Post note for track">
</form>

app/views/users/new.html.erb
<h1>Sign up yo for some sweet music!</h1>

<form action='<%=users_url%>' method="post">
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token %>">
	<label for="user_email">Email</label>
	<input type="text" name="user[email]" id="user_email">

	<label for="user_password">Password</label>
	<input type="password" name="user[password]" id="user_password">

	<input type="submit" value="Create your identity">
</form>

app/views/users/show.html.erb
Welcome, <%=@user.email%>

<%= link_to "Band Index", bands_url%>